version: "3.10"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_perplexity
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_perplexity
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:latest
    container_name: redis_perplexity
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  

  # embedding-service:
  #   build: ./python-embedding
  #   container_name: embedding_service
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./python-embedding:/app   


  nginx:
    image: nginx:latest
    container_name: nginx_perplexity
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  mongo_data:
  qdrant_data:
  redis_data:
